#!/usr/bin/env python3
"""Manual test for Module 5: ask your knowledge base a question (the RAG loop).

Prerequisites:
  * You've ingested some videos (scripts/ingest.py) WITH categorisation, and
  * LLM_API_KEY is set in .env (the grounded answer is generated by the LLM).

This runs the real pipeline: it embeds your question, retrieves the most
similar videos from ChromaDB, lazily fetches their transcripts from YouTube
(caching them back), and asks the LLM to answer strictly from those transcripts.

Usage:
    python scripts/ask.py "what have I learned about vector databases?"
    python scripts/ask.py            # then type questions interactively
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.services.llm_service import LLMNotConfiguredError  # noqa: E402
from app.services.rag_pipeline import rag_pipeline  # noqa: E402
from app.services.vector_store import vector_store  # noqa: E402


def _show(resp) -> None:
    print("\n" + "=" * 70)
    if resp.needs_confirmation:
        print(resp.answer)  # the "answer from general knowledge?" prompt
        return
    tag = "GENERAL KNOWLEDGE (not from your videos)" if resp.from_general_knowledge \
        else "GROUNDED in your watched videos"
    print(f"[{tag}]\n")
    print(resp.answer)
    if resp.sources:
        print("\nSources used:")
        for i, s in enumerate(resp.sources, 1):
            flag = "transcript" if s.transcript_used else f"title only ({s.note})"
            print(f"  [{i}] sim={s.similarity:.3f} · {flag}\n      {s.title}\n      {s.url}")
    if resp.retrieval:
        print("\nRetrieval trail (video · similarity):")
        for r in resp.retrieval:
            print(f"    {r['similarity']:.3f}  {r['title'][:60]}")
    print("=" * 70)


def _ask(question: str) -> None:
    try:
        resp = rag_pipeline.answer_question(question)
    except LLMNotConfiguredError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(2)
    _show(resp)

    # If nothing relevant was found, ask permission before general knowledge.
    if resp.needs_confirmation:
        choice = input("\nAnswer from general knowledge instead? [y/N] ").strip().lower()
        if choice in ("y", "yes"):
            _show(rag_pipeline.answer_from_general_knowledge(question))
        else:
            print("Okay — leaving it grounded only.")


def main() -> int:
    count = vector_store.count()
    if count == 0:
        print("Your knowledge base is empty. Run scripts/ingest.py first.",
              file=sys.stderr)
        return 1
    print(f"Knowledge base: {count} videos indexed.")

    if len(sys.argv) > 1:
        _ask(" ".join(sys.argv[1:]))
        return 0

    print("Type a question (or 'quit'):")
    while True:
        try:
            q = input("\n> ").strip()
        except (EOFError, KeyboardInterrupt):
            print()
            break
        if q.lower() in ("quit", "exit", "q", ""):
            break
        _ask(q)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
